//export const server = "http://localhost:5000"
export const server = "https://w3link-api.vercel.app"
export const create_account_path = "/create-account"
export const set_data_path = "/set-data"
export const get_data_path = "/get-data"